description: Gene Align and Family Aggregator
homepage_url: https://github.com/TGAC/Aequatus
name: gafa
owner: earlhaminst
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/main/tools/GAFA/
long_description: Gene Align and Family Aggregator (GAFA) generates an SQLite database that can be visualised with Aequatus, an open-source homology browser developed with novel rendering approaches to visualise homologous, orthologous and paralogous gene structures.
categories:
- Visualization
type: unrestricted
