categories:
- Computational chemistry
description: Plot heatmap of gene expression data
homepage_url: https://github.com/TGAC/earlham-galaxytools/
long_description: |
  This tool can be used to plot heatmap of gene expression data. The genes are
  chosen based on p-value, FDR, log FC and log CPM from edgeR output.
name: plotheatmap
owner: earlhaminst
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/main/tools/plotheatmap
