categories:
- Text Manipulation
description: GFF3 to JSON converter
long_description: |
	Converts GFF3 into JSON formated Gene Feature File
name: gff3_to_json
owner: tgac
remote_repository_url: https://github.com/TGAC/tgac-galaxytools/tree/master/tools/gff3_to_json
type: unrestricted
