name: rdock
owner: earlhaminst
description: small molecule - protein docking
homepage_url: http://rdock.sourceforge.net/
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/master/tools/rdock/
long_description: A Fast, Versatile and Open Source Program for Docking Ligands to Proteins and Nucleic Acids
categories: [Computational chemistry]
