name: rdock
owner: earlhaminst
description: Docking ligands to proteins and nucleic acids
homepage_url: https://rdock.github.io/
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/main/tools/rdock/
long_description: A fast, versatile and Open Source program for docking ligands to proteins and nucleic acids
categories:
- Computational chemistry
type: unrestricted
