categories:
- Computational chemistry
description: Scoring and Minimization with smina
homepage_url: https://sourceforge.net/projects/smina/
long_description: |
  smina is a fork of Autodock Vina that is customized to better support scoring
  function development and high-performance energy minimization.
name: smina
owner: earlhaminst
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/main/tools/smina/
