name: smina
owner: earlhaminst
description: smina is a fork of Autodock Vina (https://vina.scripps.edu/) that focuses on improving scoring and minimization
homepage_url: https://sourceforge.net/projects/smina/
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/main/tools/smina/
categories: [Computational chemistry]
