---
categories:
- Sequence Analysis
description: SMART domains
homepage_url: https://smart.embl.de/
name: smart_domains
owner: earlhaminst
long_description: Search domains in protein sequences using SMART
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/main/tools/smart_domains
type: unrestricted
