categories:
- Convert Formats
description: GFF3 and JSON to SQLite and FASTA header converter
homepage_url: https://github.com/TGAC/earlham-galaxytools/
long_description: Converts a set of GFF3 and JSON datasets into SQLite format, also adds species information to FASTA headers
name: gstf_preparation
owner: earlhaminst
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/master/tools/gstf_preparation
type: unrestricted
