categories:
- Convert Formats
description: GeneSeqToFamily preparation converts data for the workflow
homepage_url: https://github.com/TGAC/earlham-galaxytools/
long_description: Converts a set of GFF3 and/or JSON gene feature information datasets into SQLite format and modify the header lines of a corresponding CDS FASTA to be used with the GeneSeqToFamily workflow.
name: gstf_preparation
owner: earlhaminst
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/main/tools/gstf_preparation
type: unrestricted
