categories:
- Text Manipulation
description: Replace chromosome names
long_description: Replace chromosome names in a tabular dataset using a mapping table.
name: replace_chromosome_names
owner: earlhaminst
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/master/tools/replace_chromosome_names/
type: unrestricted
