---
categories:
- Sequence Analysis
description: Gblocks
homepage_url: https://www.biologiaevolutiva.org/jcastresana/Gblocks/Gblocks_documentation.html
name: gblocks
owner: earlhaminst
long_description: Selection of conserved blocks from multiple alignments for their use in phylogenetic analysis.
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/main/tools/gblocks
type: unrestricted
